export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET"

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST"
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS"
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL"
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET"

export const NEW_PRODUCT_REQ = "NEW_PRODUCT_REQ"
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS"
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET"
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"

export const NEW_REVIEW_REQ = "NEW_REVIEW_REQ"
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"

export const ALL_REVIEW_REQ = "ALL_REVIEW_REQ"
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS"
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL"

export const DELETE_REVIEW_REQ = "DELETE_REVIEW_REQ"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET"
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"




export const CLEAR_ERRORS = "CLEAR_ERRORS"