export const USER_LOGIN_REQ = 'USER_LOGIN_REQ'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_SIGNUP_REQ = 'USER_SIGNUP_REQ'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const LOAD_USER_REQ = 'LOAD_USER_REQ'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const UPDATE_USER_REQ = 'UPDATE_USER_REQ'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const ALL_USER_REQ = 'ALL_USER_REQ'
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS'
export const ALL_USER_FAIL = 'ALL_USER_FAIL'

export const DELETE_USER_REQ = 'DELETE_USER_REQ'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const USER_DETAILS_REQ = 'USER_DETAILS_REQ'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const UPDATE_USER_ADMIN_REQ = 'UPDATE_USER_ADMIN_REQ'
export const UPDATE_USER_ADMIN_SUCCESS = 'UPDATE_USER_ADMIN_SUCCESS'
export const UPDATE_USER_ADMIN_RESET = 'UPDATE_USER_ADMIN_RESET'
export const UPDATE_USER_ADMIN_FAIL = 'UPDATE_USER_ADMIN_FAIL'

export const UPDATE_PASSWORD_REQ = 'UPDATE_PASSWORD_REQ'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const FORGOT_PASSWORD_REQ = 'FORGOT_PASSWORD_REQ'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'